# Generated by Django 5.1.3 on 2024-11-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_remove_roomtype_price_per_night_room_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='quantity',
        ),
    ]
